#!/usr/bin/env bash

set -e

exitcode=0

report() {
  if [ $? -eq 0 ]; then
    echo -e "\e[1;32mOK\e[0m"
  else
    echo -e "\e[1;31mKO\e[0m"
    exitcode=1
  fi
}

echo -n "01-basics .. "
(cd 01-basics && bash ci)
report

echo -n "02-monads .. "
(cd 02-monads && bash ci)
report

echo -n "03-transformers .. "
(cd 03-monad-transformers && bash ci)
report

echo -n "04-extensions .. "
(cd 04-extensions && bash ci)
report

echo -n "05-laziness .. "
(cd 05-laziness && bash ci)
report

echo -n "06-prelude .. "
(cd 06-prelude && bash ci)
report

echo -n "07-text-bytestring .. "
(cd 07-text-bytestring && bash ci)
report

echo -n "29-ghc .. "
(cd 29-ghc && bash ci)
report

echo -n "30-languages .. "
(cd 30-languages && bash ci)
report

echo -n "33-categories .. "
(cd 33-categories && bash ci)
report

echo -n "34-time .. "
(cd 34-time && bash ci)
report

exit $exitcode
