#!/usr/bin/env bash

set -e

exitcode=0

echo -n "01-basics .. "
(cd 01-basics && bash ci) || exitcode=1
echo -e "\e[1;32mOK\e[0m"

echo -n "02-monads .. "
(cd 02-monads && bash ci) || exitcode=1
echo -e "\e[1;32mOK\e[0m"

echo -n "03-transformers .. "
(cd 03-monad-transformers && bash ci) || exitcode=1
echo -e "\e[1;32mOK\e[0m"

echo -n "04-extensions .. "
(cd 04-extensions && bash ci) || exitcode=1
echo -e "\e[1;32mOK\e[0m"

echo -n "05-laziness .. "
(cd 05-laziness && bash ci) || exitcode=1
echo -e "\e[1;32mOK\e[0m"

echo -n "06-prelude .. "
(cd 06-prelude && bash ci) || exitcode=1
echo -e "\e[1;32mOK\e[0m"

echo -n "07-text-bytestring .. "
(cd 07-text-bytestring && bash ci) || exitcode=1
echo -e "\e[1;32mOK\e[0m"

echo -n "29-ghc .. "
(cd 29-ghc && bash ci) || exitcode=1
echo -e "\e[1;32mOK\e[0m"

echo -n "30-languages .. "
(cd 30-languages && bash ci) || exitcode=1
echo -e "\e[1;32mOK\e[0m"

echo -n "33-categories .. "
(cd 33-categories && bash ci) || exitcode=1
echo -e "\e[1;32mOK\e[0m"

echo -n "34-time .. "
(cd 34-time && bash ci) || exitcode=1
echo -e "\e[1;32mOK\e[0m"

exit $exitcode
